version: 2

project_name: proverbilo

builds:
  - id: proverbilo
    builder: rust
    binary: proverbilo
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      - x86_64-pc-windows-gnu
    flags:
      - --release
      - --locked
      - --all-features

archives:
  - id: archives
    ids:
      - proverbilo
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Target }}"
    wrap_in_directory: "{{ .ProjectName }}-{{ .Version }}-{{ .Target }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README*
      - LICENSE*
      - CHANGELOG*
      - NOTICE*

checksum:
  name_template: checksums.txt

homebrew_casks:
  - name: proverbilo
    ids:
      - archives
    repository:
      owner: Fierthraix
      name: homebrew-tap
      token: "{{ .Env.RELEASE_PUBLISH_TOKEN }}"
    directory: Casks
    homepage: https://github.com/Fierthraix/proverbilo
    description: Programo por montri hazardajn proverbojn en Esperanto.
    license: GPL-3.0-or-later
    binaries:
      - proverbilo
scoops:
  - name: proverbilo
    ids:
      - archives
    repository:
      owner: Fierthraix
      name: scoop-bucket
      token: "{{ .Env.RELEASE_PUBLISH_TOKEN }}"
    directory: bucket
    homepage: https://github.com/Fierthraix/proverbilo
    description: Programo por montri hazardajn proverbojn en Esperanto.
    license: GPL-3.0-or-later

nix:
  - name: proverbilo
    ids:
      - archives
    repository:
      owner: Fierthraix
      name: nur-packages
      token: "{{ .Env.RELEASE_PUBLISH_TOKEN }}"
    path: pkgs/proverbilo/default.nix
    homepage: https://github.com/Fierthraix/proverbilo
    description: Programo por montri hazardajn proverbojn en Esperanto.
    license: gpl3Plus

nfpms:
  - id: packages
    ids:
      - proverbilo
    package_name: proverbilo
    vendor: Fierthraix
    homepage: https://github.com/Fierthraix/proverbilo
    maintainer: Fierthraix
    description: Programo por montri hazardajn proverbojn en Esperanto.
    license: GPL-3.0-or-later
    bindir: /usr/bin
    formats:
      - deb
      - rpm
      - apk
